### PR TITLE
Renamed Project Global Positioning Geodetic to * Geographic

### LINKED ISSUE #509: Project Global Positioning Geodetic should be named Project Global Positioning Geographic
Fits better with the entity naming (IfcGeographicCRS)

### PR DESCRIPTION
**Pull request by larswik**
Fixes #509

### CODE REVIEW

**Review by pjanck — APPROVED** [review]
lftm

**Comment by SergejMuhic** [comment]
I hope you do not expect me to regenerate the documentation just for this. 🤔

**Comment by larswik** [comment]
> I hope you do not expect me to regenerate the documentation just for this. 🤔

Nope. Did it while it was fresh. Maybe for next version?

**Review by SergejMuhic — CHANGES_REQUESTED** [review]
Could you do a merge on your fork first? I have removed the `IfcSolidStratum` concept root, so that change should resolve itself.

**Comment by larswik** [comment]
Closing this PR and create a new fresh #520.

**Pull request closed without merging**
