### PR TITLE
BookB-Pset_GeoScienceFeatureCommon

### PR DESCRIPTION
**Pull request by larswik**
# Pset: Pset_GeoScienceFeatureCommon

## Description: 

Common properties for geoscience features

| Property | Datatype | Description |
|----------|----------|-------------|
|Comment|IfcText|Additional noteworthy information related e.g. to one specific entity|

### CODE REVIEW

**Comment by SylvieBretelle** [comment]
more properties into this GeoScienceFeatureCommon : description, comment, FeatureName, linktodata, ProjectName, Chainage

**Comment by larswik** [comment]
> more properties into this GeoScienceFeatureCommon : description, comment, FeatureName, linktodata, ProjectName, Chainage

See comments in Excel sheet:
Description => IfcGeoScienceFeature.Descriptioin
Comment => Is already there (see above)!
FeatureName => IfcGeoScienceFeature.Name
linkToData => IfcRelAssociatesDataset
ProjectName => IfcProject.Name
Chainage => IfcRelPositions => IfcReferent/Pset_Stationing

=> Use mechanisms already in the schema instead of creating parallel mechanisms in Psets!

**Comment by SergejMuhic** [comment]
Quite confused with this pset. None of the common properties e. g. `Reference` in it but one peculiar one `Comment` which seems a lot like `IfcRoot`.`Description`:

"Optional description, provided for exchanging informative comments."

**Comment by larswik** [comment]
> Quite confused with this pset. None of the common properties e. g. `Reference` in it but one peculiar one `Comment` which seems a lot like `IfcRoot`.`Description`:
> 
> "Optional description, provided for exchanging informative comments."

Well, they had also a Description property specified, which I mapped to IfcRoot.Description so that one was already taken. Description from the domain team: "Any noteworthy items which could not be entered among other properties".
Comment has the description above (in PR description) from the domain team.

Regarding "Reference", we need to ask the domain team. To me it feels as if the standard properties "Reference" and "Status" seems to have more to do with man made objects.

Ping @j-weil



</body>

</html>

**Comment by larswik** [comment]
If Description and Comment is one and the same property, we could skip this Pset altogether since everything else is already in the IFC schema.

**Comment by j-weil** [comment]
I agree, if only Decription and Comment remain and this is already handled mor egenerally we do not need this Pset.

**Pull request closed without merging**
