### PR TITLE
EX-SU-Qto_ArchElementBaseQuantities

### PR DESCRIPTION
**Pull request by larswik**

### CODE REVIEW

**Comment by larswik** [comment]
@SergejMuhic : This is the result from discussions with domain team. Differs from your draft #711. Discuss?

**Review by SergejMuhic — CHANGES_REQUESTED** [review]
Length and Volume seem reusable.

**Comment by larswik** [comment]
> Length and Volume seem reusable.

From where?

**Comment by SergejMuhic** [comment]
I guess we could reconcile one of the Length and Volume quantities, but I guess it is fine. We did not reconcile the quantity sets, right?

Just found out one concerning thing, the bSI documentation does not differentiate between property and quantity:
image
👀

**Comment by larswik** [comment]
@SergejMuhic : Seems like most descriptions are specific. Can we merge?

**Comment by SergejMuhic** [comment]
Sure, let's merge. There was a unification on bSI with this description: "The length of the object." We just have not yet merged the reconcile PRs.

**Comment by SergejMuhic** [comment]
Modified descriptions to fit bsi template [modifying ArchElement Length and Volume descriptions](https://github.com/bSI-InfraRoom/IFC-Specification/pull/822/commits/0f4798fd1facb8505a21fd545d9ffb0825a5f691)

**Review by SergejMuhic — APPROVED** [review]

**Pull request merged**
