### PR TITLE
Update IfcReferent

### LINKED ISSUE #344: Removal of attribute IfcReferent.RestartDistance
As title says, we want to remove `IfcReferent.RestartDistance` in favour of the `Pset_Stationing` property set.

https://github.com/buildingSMART/IFC4.3.x-development/issues/169

### PR DESCRIPTION
**Pull request by larswik**
Deprecate RestartDistance.
Fixes #344

### CODE REVIEW

**Comment by clfey** [comment]
CLFEY : No opinion concerning removal or deprecation.

**Comment by czapplitec** [comment]
I would actually prefer to remove. There are some changes being done on the schema in parallel by bSI. We don't have to keep the "no-change-on-schema" idea.

**Comment by larswik** [comment]
If everybody agrees on a remove, I will do that. I assume that the same goes for MILEPOST and KILOPOST as well.

**Review by clfey — APPROVED** [review]

**Comment by SergejMuhic** [comment]
> I would actually prefer to remove. There are some changes being done on the schema in parallel by bSI. We don't have to keep the "no-change-on-schema" idea.

Me too. The resolution was to remove. Since it was added in 4.1 which has been withdrawn, I would say that it is safe to remove.

**Comment by larswik** [comment]
RestartDistance removed now.

**Review by czapplitec — APPROVED** [review]

**Review by SergejMuhic — APPROVED** [review]

**Pull request merged**
