### PR TITLE
Bringing back Body-Fallback

### LINKED ISSUE #30: IfcShapeRepresentation Representation Identifier Body-Fallback
https://standards.buildingsmart.org/IFC/RELEASE/IFC4/FINAL/HTML/link/ifcshaperepresentation.htm

IfcShapeRepresentation has a table listing Representation identifiers.
If you refer to the change note below, it states 'Body-Fallback' was added as an identifier in IFC4.
However it's not listed in the table.  I'd like to see it listed explicitly in the table, but was it deliberately omitted and the note was not updated?

Cheers,

Jon

### PR DESCRIPTION
**Pull request by SergejMuhic**
Resolves #30

### CODE REVIEW

**Review by AlexBrad1eyCT — APPROVED** [review]
LFTM

**Review by jmirtsch — APPROVED** [review]
Thanks for adding this.

**Comment by SergejMuhic** [comment]
I will merge this as there was no response from @TLiebich . It is not that big of a change, just bringing back somethings that was probably accidentally removed.

**Comment by TLiebich** [comment]
sorry for being late - so it is a post approval

**Pull request merged**
