### PR TITLE
jwg12 ifc segment dim

### PR DESCRIPTION
**Pull request by SergejMuhic**
1. Removed `IfcCurveSegment.Dim`
2. Added `IfcSegmentDim` function
3. Added `IfcSegment.Dim` calling `IfcSegmentDim` function

### CODE REVIEW

**Review by pjanck — APPROVED** [review]
lftm

**Comment by SergejMuhic** [comment]
Give me one more review guys please. 😄 

I really need to merge this one.

**Comment by pjanck** [comment]
Pinging @aothms @czapplitec @anborr @TLiebich @peterrdf @larswik

**Comment by TLiebich** [comment]
correct from my side

**Review by larswik — APPROVED** [review]

**Review by peterrdf — APPROVED** [review]

**Comment by SergejMuhic** [comment]
Thanks a lot!

**Pull request merged**
