### PR TITLE
IfcDatasetReference.ReferencedDataset/Description => optional

### LINKED ISSUE #500: [IFC Tunnel] IfcDatasetReference.ReferencedDataset should be optional
See [IFC Tunnel Deployment - Issue 22](https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/issues/22)

Also discovered that Description was not optional.

### PR DESCRIPTION
**Pull request by larswik**
Fixes #500 and fixes https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/issues/22 also fixes https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/issues/21

### CODE REVIEW

**Comment by larswik** [comment]
Also fixes https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/issues/21

**Review by SergejMuhic — APPROVED** [review]

**Comment by SergejMuhic** [comment]
@jmirtsch Approve would be appreciated. 😄

**Review by pjanck — APPROVED** [review]
Seems reasonable.

**Review by jmirtsch — APPROVED** [review]
Looks fine to me.

**Pull request merged**
