### PR TITLE
jwg12 Delete IfcBearingTypeDisplacementEnum

### PR DESCRIPTION
**Pull request by SergejMuhic**
1. deleted the enum and all constants

### CODE REVIEW

**Review by pjanck — APPROVED** [review]
I assume this wasn't used as a type of any attribute of any entity in the schema (I'm missing a change of such sort)?

**Comment by SergejMuhic** [comment]
Ping @jmirtsch @peterrdf @larswik @anborr @TLiebich one more review please. 😄 Thanks.

**Review by jmirtsch — APPROVED** [review]
Seems to me this enumeration is not referenced and can be deleted.

**Comment by SergejMuhic** [comment]
> Seems to me this enumeration is not referenced and can be deleted.

Correct. All the constants and the enumeration are removed in the PR.

**Pull request merged**
