### PR TITLE
Revert "Update IfcRelInterferesElement DocEntity & Documentation"

### PR DESCRIPTION
**Pull request by SergejMuhic**
Reverts bSI-InfraRoom/IFC-Specification#40

This is was not ready to merge.

### CODE REVIEW

**Comment by AlexBrad1eyCT** [comment]
Ok then!

**Comment by SergejMuhic** [comment]
Can we re-open the previous PR with all of my comments?

**Comment by AlexBrad1eyCT** [comment]
unfortunately there is no way to reopen a pull request (I looked), best option is to clone Matthieu's branch, change the push location to your repository and create a new pull request

**Comment by SergejMuhic** [comment]
That will not give us back the review I fear. So, I contacted Matthieu and asked him to look at it, then re-create the PR.

**Pull request merged**
