### PR TITLE
Pset_LinearReferencingMethod applicability

### LINKED ISSUE #346: Pset_LinearReferencingMethod ApplicableType change to IfcReferent
Applicability shall be extended to `IfcReferent` for the possibility of overriding the one set on `IfcAlignment`.

https://github.com/buildingSMART/IFC4.3.x-development/issues/169

### PR DESCRIPTION
**Pull request by larswik**
Fixes #346

### CODE REVIEW

**Review by czapplitec — APPROVED** [review]

**Review by clfey — COMMENTED** [review]
I just realised that Pset_LinearReferencingMethod is applicable to IfcAlignment. I do not see how this is meant to be used. I understand why each referent needs to know its LRM. One particular alignment may be used as the nesting element for many referents, where some referents may for instance use LRM type "1" and the others use for instance LRM type "2". The alignment will be used as the Linear Element (as per the ISO interpretation) for nesting of both type "1" and type "2" referents - but the alignment can only mention an LRM Pset once - so which of the two LRMs in use should be mentioned? A Pset cannot be present twice in the alignment. 

**Proposed solution** Remove "IfcAlignment" from the list of applicable elements for PsetLinearReferencingMethod.

**Comment by czapplitec** [comment]
Every Pset is optional for the applicable entitites. I interpret it as IfcAlignment could use Pset_LinearReferencingMethod and all the nested IfcReferents will inherit the information. If there are more than one LRM types in the nested IfcReferents, then:
- Either define LRM type for each IfcReferent, so each IfcReferent has a Pset_LinearReferencingMethod
- Or define a "main" LRM type for IfcAlignment, and the nested IfcReferents which have LRM type other than the "main" one could have Pset_LinearReferencingMethod to overwrite.

**Comment by larswik** [comment]
I share the view of @czapplitec above.

**Comment by clfey** [comment]
I see - then it makes senseto to apply the Pset to the nesting IfcAlignment as well.

**Comment by larswik** [comment]
@SergejMuhic : This seems fine for merging now.

**Review by SergejMuhic — APPROVED** [review]

**Pull request merged**
