### PR TITLE
Pset_GeoScienceFeatureTypePhysicalPropertyDistribution

### PR DESCRIPTION
**Pull request by larswik**
# Pset: Pset_GeoScienceFeatureTypePropertyDistribution

## Description: 

Properties for physical property distributions

| Property                   | Datatype | Description                                                  |
| -------------------------- | -------- | ------------------------------------------------------------ |
| SpatialCorrelationFunction | IfcText  | Definition in space of physical properties like rock mass strength or  stiffness by mathematical functions (mathematical expression as a character string). |

### CODE REVIEW

**Review by SergejMuhic — COMMENTED** [review]
Would it not make more sense to exchange this kind of information in the project documentation? In the IFC file it serves no purpose, it is impossible to format so really hard to convey any useful information. @j-weil @Michel-Rives

**Comment by SergejMuhic** [comment]
After discussion, the proposal is to add external dataset usage that would attach an equation in Latex, image etc.

**Comment by Michel-Rives** [comment]
Yes, please do this and clarify : « attach an equation specified in a .doc, .xls, Latex, png, etc. »

Thks.  M./

 

De : SergejMuhic ***@***.***> 
Envoyé : jeudi 13 juillet 2023 20:26
À : bSI-InfraRoom/IFC-Specification ***@***.***>
Cc : Michel-Rives ***@***.***>; Mention ***@***.***>
Objet : Re: [bSI-InfraRoom/IFC-Specification] Pset_GeoScienceFeatureTypePhysicalPropertyDistribution (PR #658)

 

After discussion, the proposal is to add external dataset usage that would attach an equation in Latex, image etc.

**Comment by larswik** [comment]
It should be possible to attach all necessary metadata (e.g. file type, content etc) in [IfcDatasetInformation](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcdatasetinformation.htm).

**Comment by SergejMuhic** [comment]
Agreement to create a usage for spatial correlation function #670

**Pull request closed without merging**
