### PR TITLE
Update IfcGradientCurve/Documentation.md

### PR DESCRIPTION
**Pull request by larswik**
Fixed typo

### CODE REVIEW

**Review by pjanck — APPROVED** [review]

**Review by SergejMuhic — APPROVED** [review]

**Comment by SergejMuhic** [comment]
Should be merged into develop though. I can try moving the commit later but I would prefer the change to be on develop. Should be more certain.

**Comment by SergejMuhic** [comment]
@larswik will you create a new PR based on `develop`?

**Comment by larswik** [comment]
> @larswik will you create a new PR based on `develop`?

Done!

**Comment by pjanck** [comment]
Superseded by #555

**Pull request closed without merging**
