### PR TITLE
Copyright updates

### PR DESCRIPTION
**Pull request by SergejMuhic**
Updated copyright year to 2021 for the publications that come into question.

### CODE REVIEW

**Review by pjanck — APPROVED** [review]
I'M not sure if you've found them all, but these seem right.

**Review by AlexBrad1eyCT — APPROVED** [review]
A Stefan mentioned i hope you got them all!

**Comment by SergejMuhic** [comment]
I was not aiming for all. 😄 The ones that we need for now (Scope - the generic one for all MVDs, General Usage and Publication/General).

**Review by jmirtsch — CHANGES_REQUESTED** [review]
Some other locations I found copyright is mentioned.

https://github.com/bSI-InfraRoom/IFC-Specification/blob/6d7efab75c0d338e275c818df9836ed775f1f7fc/IFC4x3/Publications/General/Documentation.md
https://github.com/bSI-InfraRoom/IFC-Specification/blob/6d7efab75c0d338e275c818df9836ed775f1f7fc/IFC4x3/Publications/Bridge%20Model%20Views/Documentation.md
https://github.com/bSI-InfraRoom/IFC-Specification/blob/6d7efab75c0d338e275c818df9836ed775f1f7fc/IFC4x3/Publications/Bridge%20Model%20Views/DocPublication.xml

Also, the contents here need to be updated.  https://github.com/buildingSMART/IfcDoc/blob/f352c3e4aeeb646bc581681ae3e6c1b98f182007/content/copyright.htm

In the last, it should also have the written correspondence notice revised to:
Written requests should be addressed to; Richard Petrie, Company Secretary & Chief Executive, buildingSMART International Limited, Kings House, Station Road, Kings Langley, WD4 8LZ, UK. Email: contact@buildingsmart.org

**Comment by SergejMuhic** [comment]
The last one I already updated. Will commit to IfcDoc (probably directly to ```development```)

**Pull request merged**
