### PR TITLE
Pset_DiscreteAccessoryTypeWaterBarrier

### PR DESCRIPTION
**Pull request by larswik**
# Pset: Pset_DiscreteAccessoryTypeWaterBarrier

## Description: 

Properties for discrete accessories of type water barrier

| Property | Datatype       | Description                                          |
| -------- | -------------- | ---------------------------------------------------- |
| Material | IfcLabel       | Use IfcMaterialDefinition - Not part of the Pset/Qto |
| SealType | PEnum_SealType | Specifies the type of seal                           |

## Enumeration: PEnum_SealType

| Constant        | Description |
| --------------- | ----------- |
| COMPRESSIBLE    |             |
| HYDRO_EXPANDING |             |
| MIXED           |             |
| GINA            |             |
| OMEGA           |             |

### CODE REVIEW

**Comment by SergejMuhic** [comment]
worries me a bit that there is no descriptions available for constants

**Comment by larswik** [comment]
> worries me a bit that there is no descriptions available for constants

I can collect all enum constants and ask the domain group.

**Comment by JontyDunn** [comment]
COMPRESSIBLE  Seal that is compressed into joint and expands to provide seal
HYDRO_EXPANDING  Hydrophilic swellable profile that swells in contact with water to provide seal
MIXED  Hybrid seal combining compressive and hydrophilic components
GINA  Proprietary compressive seal used in immersed tunnels, I don't think we need this now 
OMEGA  Proprietary membrane seal, I don't think we need this now

Add...
MEMBRANE  Flexible membrane that bridges a gap to provide seal
INFLATABLE  Seal installed in gap and inflated to provide seal

**Review by SergejMuhic — COMMENTED** [review]
> GINA Proprietary compressive seal used in immersed tunnels, I don't think we need this now
OMEGA Proprietary membrane seal, I don't think we need this now
Add...
MEMBRANE Flexible membrane that bridges a gap to provide seal
INFLATABLE Seal installed in gap and inflated to provide seal

Is this agreed in the domain team? I would not want to do something that is based on one opinion and not coordinated with the rest.

EDIT: ping @JontyDunn @michel-rives

**Comment by Michel-Rives** [comment]
Yes, that’s agreed with the Domain Team – GINA/OMEGA not needed / MEMBRANE/INFLATEBLE needed.

 

Thks.  M./

 

De : SergejMuhic ***@***.***> 
Envoyé : jeudi 13 juillet 2023 18:53
À : bSI-InfraRoom/IFC-Specification ***@***.***>
Cc : Michel-Rives ***@***.***>; Mention ***@***.***>
Objet : Re: [bSI-InfraRoom/IFC-Specification] Pset_DiscreteAccessoryTypeWaterBarrier (PR #575)

 

@SergejMuhic commented on this pull request.

GINA Proprietary compressive seal used in immersed tunnels, I don't think we need this now
OMEGA Proprietary membrane seal, I don't think we need this now
Add...
MEMBRANE Flexible membrane that bridges a gap to provide seal
INFLATABLE Seal installed in gap and inflated to provide seal

Is this agreed in the domain team? I would not want to do something that is based on one opinion and not coordinated with the rest.

EDIT: ping @JontyDunn <https://github.com/JontyDunn>  @Michel-Rives <https://github.com/Michel-Rives>

**Comment by SergejMuhic** [comment]
I cannot seem to be able to clone @larswik fork. He must have limited access. I will merge and edit.

**Review by SergejMuhic — APPROVED** [review]

**Pull request merged**
