### PR TITLE
Added project Dataset Information template

### LINKED ISSUE #497: Concept Template for Project Dataset Information
Proposal: similar to Project Documentation Information.

### PR DESCRIPTION
**Pull request by larswik**
Addressing #497. Usage still to come.

### CODE REVIEW

**Comment by larswik** [comment]
Rule ids are missing (as in Project Document Information). Don't know which would be needed.

**Review by pjanck — COMMENTED** [review]
Idea for ruleid: location, schemareference, identification?

**Review by SergejMuhic — COMMENTED** [review]
Would you follow-up on the ruleIDs and a usage? Or merge as it is?

**Comment by larswik** [comment]
> Would you follow-up on the ruleIDs and a usage? Or merge as it is?

I guess ruleids as @pjanck suggests does not hurt? Will add. Do I need to do anything more regarding the usage?

**Comment by larswik** [comment]
Ping @SergejMuhic and @pjanck .

**Comment by SergejMuhic** [comment]
> > Would you follow-up on the ruleIDs and a usage? Or merge as it is?
> 
> I guess ruleids as @pjanck suggests does not hurt? Will add. Do I need to do anything more regarding the usage?

Sure.

Regarding usage, just a reference is fine for now I guess. I cannot think of a specific configuration on `IfcProject` at the moment.

**Review by SergejMuhic — APPROVED** [review]

**Comment by SergejMuhic** [comment]
@larswik please synch your fork 😄

**Review by pjanck — APPROVED** [review]
lftm

**Pull request merged**
