### PR TITLE
removing window door style

### LINKED ISSUE #681: Remove `IfcDoorStyleConstructionEnum` and `IfcDoorStyleOperationEnum`
See https://github.com/buildingSMART/IFC4.3.x-development/issues/75

### LINKED ISSUE #684: Remove `IfcWindowStyleConstructionEnum` and `IfcWindowStyleOperationEnum`
See https://github.com/buildingSMART/IFC4.3.x-development/issues/75

### LINKED ISSUE #690: Remove `IfcDoorStyle` and `IfcWindowStyle`
See https://github.com/buildingSMART/IFC4.3.x-development/issues/75

Remove their use in Where rules as well.

### PR DESCRIPTION
**Pull request by SergejMuhic**
1. [remove window style](https://github.com/bSI-InfraRoom/IFC-Specification/commit/8edd3c3438c8c1fd6c8158edafad834f2c5027ca)
2. [remove door style](https://github.com/bSI-InfraRoom/IFC-Specification/commit/c481d446627bffee9fc747f945288ac1167afcfb)
3. [keeping documentation of window and door style](https://github.com/bSI-InfraRoom/IFC-Specification/commit/4fcd6572ef15166a5778b783d75b32afe54f8a48)
4. [remove IfcWindowStyleConstructionEnum and IfcWindowStyleOperationEnum](https://github.com/bSI-InfraRoom/IFC-Specification/pull/706/commits/38df347db3dff4bf1e76d32d492eb0fa3e434948)
5. [remove IfcDoorStyleConstructionEnum and IfcDoorStyleOperationEnum](https://github.com/bSI-InfraRoom/IFC-Specification/pull/706/commits/a2ec7ccf96e83fd5d250a6f39950ba59b6298f97)

### CODE REVIEW

**Review by larswik — COMMENTED** [review]
I am not sure how this works. IfcDoorStyle/IfcWindowStyle deprecated in Coordination View and deleted from the schema?

**Comment by SergejMuhic** [comment]
> I am not sure how this works. IfcDoorStyle/IfcWindowStyle deprecated in Coordination View and deleted from the schema?

I was looking at that also. This was some automatic stuff that happened there. Let me review that again.

**Comment by SergejMuhic** [comment]
I have added the enum removal issues to this PR also. Let's do everything in one.

**Comment by SergejMuhic** [comment]
I will leave the change to General Usage for now. It seems like a waste just dumping that documentation. Apparently the entity description was copied over to the concept root. Nice mechanism that I knew nothing about. 😄

**Pull request merged**
